create table actstream_follow
(
    id              integer generated by default as identity
        primary key,
    object_id       varchar(255)             not null,
    actor_only      boolean                  not null,
    started         timestamp with time zone not null,
    content_type_id integer                  not null
        constraint actstream_follow_content_type_id_ba287eb9_fk_django_co
            references django_content_type
            deferrable initially deferred,
    user_id         integer                  not null
        constraint actstream_follow_user_id_e9d4e1ff_fk_auth_user_id
            references auth_user
            deferrable initially deferred,
    flag            varchar(255)             not null,
    constraint actstream_follow_user_id_content_type_id__b3632d76_uniq
        unique (user_id, content_type_id, object_id, flag)
);

alter table actstream_follow
    owner to rkse;

create index actstream_follow_object_id_d790e00d
    on actstream_follow (object_id);

create index actstream_follow_object_id_d790e00d_like
    on actstream_follow (object_id varchar_pattern_ops);

create index actstream_follow_started_254c63bd
    on actstream_follow (started);

create index actstream_follow_content_type_id_ba287eb9
    on actstream_follow (content_type_id);

create index actstream_follow_user_id_e9d4e1ff
    on actstream_follow (user_id);

create index actstream_follow_flag_0e741c24
    on actstream_follow (flag);

create index actstream_follow_flag_0e741c24_like
    on actstream_follow (flag varchar_pattern_ops);

