create table actstream_action
(
    id                            integer generated by default as identity
        primary key,
    actor_object_id               varchar(255)             not null,
    verb                          varchar(255)             not null,
    description                   text,
    target_object_id              varchar(255),
    action_object_object_id       varchar(255),
    timestamp                     timestamp with time zone not null,
    public                        boolean                  not null,
    action_object_content_type_id integer
        constraint actstream_action_action_object_conten_ee623c15_fk_django_co
            references django_content_type
            deferrable initially deferred,
    actor_content_type_id         integer                  not null
        constraint actstream_action_actor_content_type_i_d5e5ec2a_fk_django_co
            references django_content_type
            deferrable initially deferred,
    target_content_type_id        integer
        constraint actstream_action_target_content_type__187fa164_fk_django_co
            references django_content_type
            deferrable initially deferred
);

alter table actstream_action
    owner to rkse;

create index actstream_action_actor_object_id_72ef0cfa
    on actstream_action (actor_object_id);

create index actstream_action_actor_object_id_72ef0cfa_like
    on actstream_action (actor_object_id varchar_pattern_ops);

create index actstream_action_verb_83f768b7
    on actstream_action (verb);

create index actstream_action_verb_83f768b7_like
    on actstream_action (verb varchar_pattern_ops);

create index actstream_action_target_object_id_e080d801
    on actstream_action (target_object_id);

create index actstream_action_target_object_id_e080d801_like
    on actstream_action (target_object_id varchar_pattern_ops);

create index actstream_action_action_object_object_id_6433bdf7
    on actstream_action (action_object_object_id);

create index actstream_action_action_object_object_id_6433bdf7_like
    on actstream_action (action_object_object_id varchar_pattern_ops);

create index actstream_action_timestamp_a23fe3ae
    on actstream_action (timestamp);

create index actstream_action_public_ac0653e9
    on actstream_action (public);

create index actstream_action_action_object_content_type_id_ee623c15
    on actstream_action (action_object_content_type_id);

create index actstream_action_actor_content_type_id_d5e5ec2a
    on actstream_action (actor_content_type_id);

create index actstream_action_target_content_type_id_187fa164
    on actstream_action (target_content_type_id);

