create table auth_user
(
    id           integer generated by default as identity
        primary key,
    password     varchar(128)             not null,
    last_login   timestamp with time zone,
    is_superuser boolean                  not null,
    username     varchar(150)             not null
        unique,
    first_name   varchar(150)             not null,
    last_name    varchar(150)             not null,
    email        varchar(254)             not null,
    is_staff     boolean                  not null,
    is_active    boolean                  not null,
    date_joined  timestamp with time zone not null
);

alter table auth_user
    owner to rkse;

create index auth_user_username_6821ab7c_like
    on auth_user (username varchar_pattern_ops);

INSERT INTO public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) VALUES (1, 'pbkdf2_sha256$600000$WkN3WMIJp408Adacz9d774$wNAmCvfQDNciWUDlyAg9bwtfCOIOwopN4bgeAq2oiU4=', '2023-07-18 21:38:53.287781 +00:00', true, 'rkse', '', '', '', true, true, '2023-07-18 21:38:17.057848 +00:00');
