create table auth_permission
(
    id              integer generated by default as identity
        primary key,
    name            varchar(255) not null,
    content_type_id integer      not null
        constraint auth_permission_content_type_id_2f476e4b_fk_django_co
            references django_content_type
            deferrable initially deferred,
    codename        varchar(100) not null,
    constraint auth_permission_content_type_id_codename_01ab375a_uniq
        unique (content_type_id, codename)
);

alter table auth_permission
    owner to rkse;

create index auth_permission_content_type_id_2f476e4b
    on auth_permission (content_type_id);

INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add user', 4, 'add_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change user', 4, 'change_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete user', 4, 'delete_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can view user', 4, 'view_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can add content type', 5, 'add_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can change content type', 5, 'change_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can delete content type', 5, 'delete_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can view content type', 5, 'view_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can add session', 6, 'add_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can change session', 6, 'change_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can delete session', 6, 'delete_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can view session', 6, 'view_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add site', 7, 'add_site');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change site', 7, 'change_site');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete site', 7, 'delete_site');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can view site', 7, 'view_site');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can add action', 8, 'add_action');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can change action', 8, 'change_action');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can delete action', 8, 'delete_action');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can view action', 8, 'view_action');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can add follow', 9, 'add_follow');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can change follow', 9, 'change_follow');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can delete follow', 9, 'delete_follow');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can view follow', 9, 'view_follow');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add user', 10, 'add_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change user', 10, 'change_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete user', 10, 'delete_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can view user', 10, 'view_user');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can add message', 11, 'add_message');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can change message', 11, 'change_message');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can delete message', 11, 'delete_message');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can view message', 11, 'view_message');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can add comment', 12, 'add_comment');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can change comment', 12, 'change_comment');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can delete comment', 12, 'delete_comment');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can view comment', 12, 'view_comment');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can add document', 13, 'add_document');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can change document', 13, 'change_document');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can delete document', 13, 'delete_document');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (52, 'Can view document', 13, 'view_document');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (53, 'Can add tag', 14, 'add_tag');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (54, 'Can change tag', 14, 'change_tag');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (55, 'Can delete tag', 14, 'delete_tag');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (56, 'Can view tag', 14, 'view_tag');
