create table conversation_manager_comment
(
    id              integer generated by default as identity
        primary key,
    text            varchar(260)             not null,
    created_at      timestamp with time zone not null,
    visible         boolean                  not null,
    up_votes        integer                  not null,
    down_votes      integer                  not null,
    author_id       bigint                   not null
        constraint conversation_manager_author_id_67b5ec62_fk_user_mana
            references user_manager_user
            deferrable initially deferred,
    ref_comment_id  integer
        constraint conversation_manager_ref_comment_id_e76d24f9_fk_conversat
            references conversation_manager_comment
            deferrable initially deferred,
    ref_document_id integer
        constraint conversation_manager_ref_document_id_9ff0d60c_fk_document_
            references document_manager_document
            deferrable initially deferred
);

alter table conversation_manager_comment
    owner to rkse;

create index conversation_manager_comment_author_id_67b5ec62
    on conversation_manager_comment (author_id);

create index conversation_manager_comment_ref_comment_id_e76d24f9
    on conversation_manager_comment (ref_comment_id);

create index conversation_manager_comment_ref_document_id_9ff0d60c
    on conversation_manager_comment (ref_document_id);

INSERT INTO public.conversation_manager_comment (id, text, created_at, visible, up_votes, down_votes, author_id, ref_comment_id, ref_document_id) VALUES (2, 'This is a good document', '2023-07-18 21:45:08.000000 +00:00', true, 0, 0, 2, null, 2);
