create table django_content_type
(
    id        integer generated by default as identity
        primary key,
    app_label varchar(100) not null,
    model     varchar(100) not null,
    constraint django_content_type_app_label_model_76bd3d3b_uniq
        unique (app_label, model)
);

alter table django_content_type
    owner to rkse;

INSERT INTO public.django_content_type (id, app_label, model) VALUES (1, 'admin', 'logentry');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (2, 'auth', 'permission');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (3, 'auth', 'group');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (4, 'auth', 'user');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (5, 'contenttypes', 'contenttype');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (6, 'sessions', 'session');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (7, 'sites', 'site');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (8, 'actstream', 'action');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (9, 'actstream', 'follow');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (10, 'user_manager', 'user');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (11, 'conversation_manager', 'message');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (12, 'conversation_manager', 'comment');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (13, 'document_manager', 'document');
INSERT INTO public.django_content_type (id, app_label, model) VALUES (14, 'tag_manager', 'tag');
