create table django_migrations
(
    id      bigint generated by default as identity
        primary key,
    app     varchar(255)             not null,
    name    varchar(255)             not null,
    applied timestamp with time zone not null
);

alter table django_migrations
    owner to rkse;

INSERT INTO public.django_migrations (id, app, name, applied) VALUES (1, 'contenttypes', '0001_initial', '2023-07-18 21:38:08.075867 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (2, 'auth', '0001_initial', '2023-07-18 21:38:08.111075 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (3, 'actstream', '0001_initial', '2023-07-18 21:38:08.145305 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (4, 'actstream', '0002_remove_action_data', '2023-07-18 21:38:08.148996 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (5, 'actstream', '0003_add_follow_flag', '2023-07-18 21:38:08.164785 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (6, 'admin', '0001_initial', '2023-07-18 21:38:08.175305 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (7, 'admin', '0002_logentry_remove_auto_add', '2023-07-18 21:38:08.180146 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (8, 'admin', '0003_logentry_add_action_flag_choices', '2023-07-18 21:38:08.185256 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (9, 'contenttypes', '0002_remove_content_type_name', '2023-07-18 21:38:08.196831 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (10, 'auth', '0002_alter_permission_name_max_length', '2023-07-18 21:38:08.202304 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (11, 'auth', '0003_alter_user_email_max_length', '2023-07-18 21:38:08.207452 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (12, 'auth', '0004_alter_user_username_opts', '2023-07-18 21:38:08.212175 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (13, 'auth', '0005_alter_user_last_login_null', '2023-07-18 21:38:08.217021 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (14, 'auth', '0006_require_contenttypes_0002', '2023-07-18 21:38:08.219061 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (15, 'auth', '0007_alter_validators_add_error_messages', '2023-07-18 21:38:08.224493 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (16, 'auth', '0008_alter_user_username_max_length', '2023-07-18 21:38:08.231280 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (17, 'auth', '0009_alter_user_last_name_max_length', '2023-07-18 21:38:08.236374 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (18, 'auth', '0010_alter_group_name_max_length', '2023-07-18 21:38:08.242169 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (19, 'auth', '0011_update_proxy_permissions', '2023-07-18 21:38:08.247155 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (20, 'auth', '0012_alter_user_first_name_max_length', '2023-07-18 21:38:08.252369 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (21, 'user_manager', '0001_initial', '2023-07-18 21:38:08.258164 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (22, 'tag_manager', '0001_initial', '2023-07-18 21:38:08.265691 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (23, 'document_manager', '0001_initial', '2023-07-18 21:38:08.282948 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (24, 'conversation_manager', '0001_initial', '2023-07-18 21:38:08.300918 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (25, 'sessions', '0001_initial', '2023-07-18 21:38:08.307899 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (26, 'sites', '0001_initial', '2023-07-18 21:38:08.311551 +00:00');
INSERT INTO public.django_migrations (id, app, name, applied) VALUES (27, 'sites', '0002_alter_domain_unique', '2023-07-18 21:38:08.318118 +00:00');
