create table document_manager_document
(
    id                 integer generated by default as identity
        primary key,
    title              varchar(200)             not null
        unique,
    created_at         timestamp with time zone not null,
    text               varchar(10000)           not null,
    up_votes           integer                  not null,
    down_votes         integer                  not null,
    status             integer                  not null,
    assignee_id        bigint
        constraint document_manager_doc_assignee_id_56d10909_fk_user_mana
            references user_manager_user
            deferrable initially deferred,
    author_id          bigint                   not null
        constraint document_manager_doc_author_id_4990a8cb_fk_user_mana
            references user_manager_user
            deferrable initially deferred,
    last_updated_by_id bigint
        constraint document_manager_doc_last_updated_by_id_950f6f8d_fk_user_mana
            references user_manager_user
            deferrable initially deferred
);

alter table document_manager_document
    owner to rkse;

create index document_manager_document_title_df4a5f77_like
    on document_manager_document (title varchar_pattern_ops);

create index document_manager_document_assignee_id_56d10909
    on document_manager_document (assignee_id);

create index document_manager_document_author_id_4990a8cb
    on document_manager_document (author_id);

create index document_manager_document_last_updated_by_id_950f6f8d
    on document_manager_document (last_updated_by_id);

INSERT INTO public.document_manager_document (id, title, created_at, text, up_votes, down_votes, status, assignee_id, author_id, last_updated_by_id) VALUES (2, 'Test Doc', '2023-07-18 21:44:48.000000 +00:00', 'This is a test doc.', 0, 0, 1, null, 2, null);
