create table tag_manager_tag
(
    id             integer generated by default as identity
        primary key,
    name           varchar(200)             not null
        unique,
    created_at     timestamp with time zone not null,
    tag_creator_id bigint                   not null
        constraint tag_manager_tag_tag_creator_id_211d4b5b_fk_user_manager_user_id
            references user_manager_user
            deferrable initially deferred
);

alter table tag_manager_tag
    owner to rkse;

create index tag_manager_tag_name_0addb287_like
    on tag_manager_tag (name varchar_pattern_ops);

create index tag_manager_tag_tag_creator_id_211d4b5b
    on tag_manager_tag (tag_creator_id);

INSERT INTO public.tag_manager_tag (id, name, created_at, tag_creator_id) VALUES (2, 'Critical', '2023-07-18 21:45:23.000000 +00:00', 2);
